# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
__all__ = [
    "EmptyProcError",
    "IconError",
    "MissingProcError",
    "MissingTypeError",
    "PathError",
]

class EmptyProcError(builtins.Exception):
    ...

class IconError(builtins.Exception):
    ...

class MissingProcError(builtins.Exception):
    ...

class MissingTypeError(builtins.Exception):
    ...

class PathError(builtins.Exception):
    ...

