# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import enum
import os
import pathlib
import typing
from . import ast
from . import exceptions
__all__ = [
    "Coord3",
    "DME",
    "DMI",
    "DMM",
    "Dir",
    "Dmlist",
    "IconState",
    "NewCall",
    "Path",
    "ProcArg",
    "ProcDecl",
    "SourceLoc",
    "Tile",
    "TypeDecl",
    "VarDecl",
    "ast",
    "exceptions",
    "version",
]

@typing.final
class Coord3:
    r"""
    A three-dimensional integer coordinate. These are currently only returned by
    certain DMM properties, and are not constructable.
    """
    @property
    def x(self) -> builtins.int: ...
    @property
    def y(self) -> builtins.int: ...
    @property
    def z(self) -> builtins.int: ...

@typing.final
class DME:
    r"""
    A representation of a single Dreammaker environment.
    """
    @property
    def filepath(self) -> pathlib.Path:
        r"""
        The original filename of the DME.
        """
    @property
    def types(self) -> builtins.dict[Path, TypeDecl]:
        r"""
        A mapping of paths in the DME to their TypeDecls.
        """
    @staticmethod
    def from_file(filename: os.PathLike | builtins.str, parse_procs: builtins.bool = False) -> DME:
        r"""
        Creates a DME from the given `filename`.
        
        If parse_procs is True, the entire AST of the codebase is traversed.
        This is slower than the default but provides more reflection
        information.
        """
    def typesof(self, prefix: Path | builtins.str) -> builtins.list[Path]:
        r"""
        Returns a list of type paths with the given `prefix`.
        """
    def subtypesof(self, prefix: Path | builtins.str) -> builtins.list[Path]:
        r"""
        Returns a list of type paths with the given `prefix`, excluding `prefix` itself.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DMI:
    r"""
    A DMI file.
    """
    @property
    def filepath(self) -> typing.Optional[pathlib.Path]:
        r"""
        The original filename of the DMI.
        """
    @property
    def icon_width(self) -> builtins.int:
        r"""
        The width of icons in the DMI.
        """
    @property
    def icon_height(self) -> builtins.int:
        r"""
        The height of icons in the DMI.
        """
    @property
    def states(self) -> collections.abc.Iterator[IconState]:
        r"""
        The states in the DMI.
        """
    @property
    def icon_dims(self) -> tuple[builtins.int, builtins.int]:
        r"""
        The width and height of icons in the DMI.
        """
    @staticmethod
    def new(dims: tuple[builtins.int, builtins.int]) -> DMI:
        r"""
        Creates an empty DMI file with the given icon width-height tuple `dims`.
        """
    @staticmethod
    def from_file(filename: os.PathLike | builtins.str) -> DMI:
        r"""
        Creates a DMI from the given `filename`.
        """
    def state_names(self) -> typing.Any:
        r"""
        Return a list of strings containing all state names in the file.
        """
    def state(self, value: builtins.str) -> IconState:
        r"""
        Return the icon state with the given `name`. If there are duplicates,
        only the first one is returned. Use `states` to retrieve duplicates.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def save_to(self, filename: typing.Any, compress: builtins.int = 0) -> None:
        r"""
        Saves the DMI to the given `filename`.
        """

@typing.final
class DMM:
    r"""
    A DMM file.
    """
    @property
    def size(self) -> Coord3:
        r"""
        The number of tiles in each of the map's three dimensions.
        """
    @property
    def filepath(self) -> pathlib.Path:
        r"""
        The original filename of the DMM.
        """
    @staticmethod
    def from_file(filename: os.PathLike | builtins.str) -> DMM:
        r"""
        Creates a DMM from the given `filename`.
        """
    def save_to(self, filename: typing.Any) -> None:
        r"""
        Saves the DMM to the given `filename`.
        """
    def tiledef(self, x: builtins.int, y: builtins.int, z: builtins.int) -> Tile:
        r"""
        Return the tile definition at coords (`x`, `y`, `z`).
        """
    def coords(self) -> collections.abc.Iterator[tuple[int, int, int]]:
        r"""
        Return an iterator over all possible 3D coordinates in the map.
        """
    def tiles(self) -> collections.abc.Iterator[Tile]:
        r"""
        Return an iterator over all unique tiles in the map.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Dmlist:
    r"""
    A primitive, read-only representation of a DM list. This is used when
    returning constant values of lists from the AST walker, and prefab values
    from the DMM reader. They are not constructable.
    
    Dmlists only support iterating over keys, and indexing with keys.
    """
    def keys(self) -> collections.abc.Iterator[typing.Any]:
        r"""
        Iterates over the keys in the list.
        """
    def __getitem__(self, item: typing.Any) -> typing.Any: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class IconState:
    r"""
    A single icon state in a DMI file.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        The state name.
        """
    @name.setter
    def name(self, value: builtins.str) -> None:
        r"""
        The state name.
        """
    @property
    def dir_count(self) -> builtins.int:
        r"""
        The number of directions in the icon state, either 1, 4, or 8.
        """
    @property
    def frames(self) -> builtins.int:
        r"""
        The number of frames in the icon state.
        """
    @property
    def delay(self) -> builtins.list[builtins.float]:
        r"""
        The icon's frame delays.
        """
    @property
    def loop_flag(self) -> builtins.int:
        r"""
        The number of times the icon animation loops, or 0 for indefinitely.
        """
    @property
    def rewind(self) -> builtins.bool:
        r"""
        Whether the icon animates both backwards and forwards.
        """
    @property
    def movement(self) -> builtins.bool:
        r"""
        Whether or not the state is a movement state.
        """
    @property
    def dirs(self) -> list:
        r"""
        The directions available in the icon state.
        """
    @staticmethod
    def from_data(data: typing.Mapping[Dir, typing.Sequence[bytes]], width: builtins.int = 32, height: builtins.int = 32, name: builtins.str = '', delays: typing.Optional[typing.Sequence[builtins.float]] = None, loops: builtins.int = 0, rewind: builtins.bool = False, movement: builtins.bool = False) -> IconState:
        r"""
        Creates an IconState with the given frame `data`, which must be a dict
        of Dirs to arrays of RGBA8 image byte data.
        """
    def data_rgba8(self, frame: builtins.int, dir: typing.Any) -> bytes:
        r"""
        Return the byte data of the spritesheet in 8-bit RGBA.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class NewCall:
    r"""
    A `new` call appearing in a constant-value position.
    """
    @property
    def path(self) -> typing.Optional[Path]:
        r"""
        The type being instantiated, or `None` for an implicit `new()`.
        """
    @property
    def args(self) -> typing.Optional[Dmlist]:
        r"""
        The constructor arguments.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Path:
    r"""
    A DM typepath.
    """
    @property
    def abs(self) -> builtins.str:
        r"""
        Returns the *absolute* representation of the path, rooted at `/datum`.
        """
    @property
    def rel(self) -> builtins.str:
        r"""
        Returns the *relative* or *declared* representation of the path.
        """
    @property
    def parent(self) -> Path:
        r"""
        The parent path.
        """
    @property
    def stem(self) -> builtins.str:
        r"""
        The final part of the path.
        """
    @property
    def is_root(self) -> builtins.bool:
        r"""
        Whether or not the path is `/`.
        """
    def __new__(cls, value: builtins.str) -> Path:
        r"""
        Returns a new path.
        """
    def child_of(self, other: typing.Any, strict: builtins.bool = False) -> builtins.bool:
        r"""
        Returns whether the path is a child of `other`.
        
        If `strict` is true, the current path will not be considered a child of
        itself.
        """
    def parent_of(self, other: typing.Any, strict: builtins.bool = False) -> builtins.bool:
        r"""
        Returns whether the path is a parent of `other`.
        
        If `strict` is true, the current path will not be considered a parent of
        itself.
        """
    def __hash__(self) -> builtins.int: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __richcmp__(self, other: typing.Any, op: int) -> builtins.bool: ...
    def __truediv__(self, other: typing.Any) -> Path:
        r"""
        Return the path with the specified suffix.
        """

@typing.final
class ProcArg:
    r"""
    A representation of a proc declaration argument.
    """
    @property
    def arg_name(self) -> builtins.str:
        r"""
        The argument name.
        """
    @property
    def arg_type(self) -> typing.Optional[Path]:
        r"""
        The argument type, if available.
        """

@typing.final
class ProcDecl:
    r"""
    A single proc declaration.
    """
    @property
    def type_path(self) -> typing.Any:
        r"""
        The type path the proc is declared on.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        The name of the proc.
        """
    @property
    def args(self) -> builtins.list[ProcArg]: ...
    @property
    def source_loc(self) -> SourceLoc:
        r"""
        The source location of the proc declaration.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def walk(self, walker: typing.Any) -> None:
        r"""
        Walks the proc AST with *walker*, calling any `visit_*` method names on
        *walker* if they exist for AST node types.
        """

@typing.final
class SourceLoc:
    r"""
    Information about the location of a source token in the tree.
    """
    @property
    def file_path(self) -> typing.Optional[pathlib.Path]:
        r"""
        The file path of the source location.
        """
    @property
    def line(self) -> builtins.int:
        r"""
        The line number, starting at 1.
        """
    @property
    def column(self) -> builtins.int:
        r"""
        The column number, starting at 1.
        """

@typing.final
class Tile:
    r"""
    An individual map tile definition.
    """
    @property
    def area_path(self) -> Path:
        r"""
        Returns the path of the tile's area. Returns only the first area if
        multiple exist.
        """
    @property
    def turf_path(self) -> Path:
        r"""
        Returns the path of the tile's turf. Returns only the first area if
        multiple exist.
        """
    def add_path(self, index: builtins.int, entry: typing.Any) -> None:
        r"""
        Add a prefab with the given `path` at `index`.
        """
    def convert(self) -> typing.Any:
        r"""
        Convert the tile definition to a Python data structure.
        
        The result of `convert` is completely disassociated from the map tile
        definition, and modifying it will have no effect on the original tile.
        """
    def del_prefab(self, index: builtins.int) -> None:
        r"""
        Deletes the prefab at `index`.
        """
    def del_prefab_var(self, index: builtins.int, name: builtins.str) -> None: ...
    def find(self, prefix: typing.Any, exact: builtins.bool = False) -> builtins.list[builtins.int]:
        r"""
        Return the indexes of the prefabs prefixed with the given path `prefix`.
        If exact is True, then the prefab path must match exactly.
        """
    def only(self, prefix: typing.Any, exact: builtins.bool = False) -> typing.Any:
        r"""
        Returns the index of the only prefab with the given `prefix`, or None if
        no such prefab exists. Raises an error if there is more than one prefab
        with the given prefix. If exact is True, then the prefab path must match
        exactly.
        """
    def prefab_path(self, index: builtins.int) -> Path:
        r"""
        Return the path of the prefab at `index`.
        """
    def prefab_var(self, index: builtins.int, name: builtins.str) -> typing.Any:
        r"""
        Return the value of the property `name` on the prefab at `index`.
        
        Raises an error if the property does not exist. For a method that
        returns a default if the property does not exist, see get_prefab_var.
        """
    def get_prefab_var(self, index: builtins.int, name: builtins.str, default: typing.Optional[typing.Any] = None) -> typing.Any:
        r"""
        Returns the value of the property `name` on the prefab at `index`. If
        the property does not exist, return `default`.
        """
    def prefab_vars(self, index: builtins.int) -> builtins.list[builtins.str]:
        r"""
        Return the list of variable names on the prefab at `index`.
        """
    def set_prefab_var(self, atom_index: builtins.int, name: builtins.str, val: typing.Any) -> None:
        r"""
        Set the value of the variable `name` to `val` at `index`.
        """
    def set_path(self, index: builtins.int, path: typing.Any) -> None:
        r"""
        Set the path of the prefab at `index` to `path`.
        """
    def make_unique(self) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __ne__(self, other: typing.Any) -> builtins.bool: ...

@typing.final
class TypeDecl:
    r"""
    A single type declaration.
    """
    @property
    def path(self) -> Path:
        r"""
        The typepath of the TypeDecl.
        """
    @property
    def source_loc(self) -> SourceLoc:
        r"""
        The location of the TypeDecl's first declaration in source.
        """
    def var_names(self, declared: builtins.bool = False, modified: builtins.bool = False, unmodified: builtins.bool = False) -> builtins.list[builtins.str]:
        r"""
        Return a list of variable names for the type declaration.
        """
    def var_decl(self, name: builtins.str, parents: builtins.bool = True) -> VarDecl:
        r"""
        Return the var declaration for variable *name*. If *parents* is True,
        check up type path if this type does not have this variable set.
        """
    def proc_names(self, declared: builtins.bool = False, modified: builtins.bool = False, unmodified: builtins.bool = False) -> builtins.list[builtins.str]:
        r"""
        Return a list of proc names for the type declaration.
        """
    def proc_decls(self, name: typing.Optional[builtins.str] = None) -> builtins.list[ProcDecl]:
        r"""
        Return proc declarations for the type. If *name* is set, only return
        proc declarations with this name.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class VarDecl:
    r"""
    A single variable declaration.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        The name of the variable.
        """
    @property
    def type_path(self) -> typing.Any:
        r"""
        The type path the proc is declared on.
        """
    @property
    def declared_type(self) -> typing.Optional[Path]:
        r"""
        The declared type of the variable, if specified.
        """
    @property
    def const_val(self) -> typing.Optional[typing.Any]:
        r"""
        The variable's value, if it can be evaluated as a constant expression.
        """
    @property
    def source_loc(self) -> SourceLoc:
        r"""
        The location of the variable declaration in the source tree.
        """

@typing.final
class Dir(enum.Enum):
    r"""
    An enumeration of directions used in icons.
    """
    NORTH = ...
    SOUTH = ...
    EAST = ...
    WEST = ...
    NORTHEAST = ...
    NORTHWEST = ...
    SOUTHEAST = ...
    SOUTHWEST = ...

def version() -> builtins.str: ...

